app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
//RUTAS DE USUARIOS NORMALES-LECTORES

/*Route::get('/',['as' => 'normal.index', function(){
	return view('normal.index');
}]);*/

Route::get('/',
	['as' => 'normal.index', 
	'uses' => 'NormalController@index'
	]);
Route::get('categories/{name}',[
	'uses'=>'NormalController@searchCategory',
	'as'=> 'normal.search.category'

	]);
Route::get('tags/{name}',[
	'uses'=>'NormalController@searchTag',
	'as'=> 'normal.search.tag'

	]);
Route::get('articles/{id}',[
	'uses' => 'NormalController@viewArticle',
	'as' => 'normal.view.article'

	]);
//RUTAS DE ADMINISTRACION


Route::group(['prefix' =>'admin','middleware' =>'auth'],function(){

	Route::get('/',['as'=>'admin.index', function() {
    return view('admin.index');//welcome

}]);
//VALIDACION PARA NEGAR OPCIONES DE USUARIO SI NO ES DE TIPO ADMIN
	Route::group(['middleware'=>'admin'], function(){

		Route::resource('users','UsersController');
		
		Route::get('users/{id}/destroy', [
		'uses' => 'UsersController@destroy',
		'as' => 'admin.users.destroy'
		]);

	});
	
	Route::resource('categories','CategoriesController');

	Route::get('categories/{id}/destroy', [
	'uses' => 'CategoriesController@destroy',
	'as' => 'admin.categories.destroy'
	]);

	Route::resource('tags','TagsController');

	Route::get('tags/{id}/destroy', [
	'uses' => 'TagsController@destroy',
	'as' => 'admin.tags.destroy'
	]);

	Route::resource('articles','ArticlesController');
	Route::get('articles/{id}/destroy', [
	'uses' => 'ArticlesController@destroy',
	'as' => 'admin.articles.destroy'
	]);

	Route::get('images',[
		'uses' => 'ImagesController@index',
		'as' => 'admin.images.index'
		]);

});

	Route::get('admin/auth/login', [
		'uses' => 'Auth\AuthController@getLogin',
		'as' => 'admin.auth.login'
		]);
	Route::post('admin/auth/login', [
		'uses' => 'Auth\AuthController@postLogin',
		'as' => 'admin.auth.login'
		]);
	/*
	Route::get('auth/logout', 'Auth\AuthController@logout');
	solo se cambia "getLogout" por  "logout" abajo
	 */
	Route::get('admin/auth/logout', [
		'uses' => 'Auth\AuthController@logout',
		'as' => 'admin.auth.logout'
		]);

resources/views/admin/template/partials/errors.blade.php
@if(count($errors) > 0)
	<div class="alert alert-success mensajesAll">
		<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
		@foreach($errors->all() as $error)
		<ul>
			<li> {{ $error }} </li>
		</ul>
			
		@endforeach
	</div>
@endif
@if(!session('mensajetrue')==null)
	<div class="alert alert-success mensajesAll">
	 <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
	{{session('mensajetrue')}}
	</div>
@endif

@if(!session('mensajefalse')==null)
	<div class="alert alert-danger mensajesAll">
	 <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
	{{session('mensajefalse')}}
	</div>
@endif

@if(!session('mensajeedit')==null)
	<div class="alert alert-success mensajesAll">
	 <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
	{{session('mensajeedit')}}
	</div>
@endif

resources/views/admin/template/partials/nav.blade.php
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{route('admin.index')}}">ADMINISTRACION</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    @if(Auth::user())
      <ul class="nav navbar-nav">
         @if(Auth::user()->admin())
        <li><a href="{{ route('admin.users.index')}}">Usuarios</a></li>
        @endif
        <li><a href="{{ route('admin.categories.index')}}">Categorias</a></li>
        <li><a href="{{ route('admin.articles.index') }}">Articulos</a></li>
        <li><a href="{{ route('admin.images.index') }}">Imagenes</a></li>
        <li><a href="{{ route('admin.tags.index')}}">Tags</a></li>
      </ul>
    
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{{ route('normal.index')}}" target="_blank">Pagina principal</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ Auth::user()->name }} <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{{ route('admin.auth.logout') }}">Salir</a></li>
          </ul>
        </li>
      </ul>
      @endif
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>